# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true 
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn

      - name: Linting
        run: |
          pip install flake8
          flake8 iris.py

    #   - name: Run Tests
    #     run: |
    #       python iris_model.py
      - name: Run Tests
        run: |
           python -m unittest discover

      - name: Deploy Model
        run: echo "Deployment step here"
